force-app/main/default/objects/Case/fields/company__c.field-meta.xml
<CustomField>
    <fullName>company__c</fullName>
    <description>Stores company name</description>
    <label>company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <label>Full Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/quest_MSP_Information.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-09-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class quest_MSP_Information {
    @AuraEnabled
    public static void createCase(Map<String,String> newCase) {
        System.debug(newCase);
        Case addCase = new Case(
            FullName__c = newCase.get('FisrtName') + ' ' + newCase.get('LastName'),
            Status = 'New',
            Origin = 'Web',
            company__c = newCase.get('Company'),
            Phone__c = newCase.get('Phone'),
            Email__c = newCase.get('Email'),
            Description = newCase.get('Looking')
        );

        insert addCase;

        System.debug(addCase);
    }
}